# Generated by Django 5.1.1 on 2024-10-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='usuario',
            new_name='Responsable_Del_Proyecto',
        ),
    ]
