# Generated by Django 5.1.1 on 2024-10-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0004_rename_responsable_task_empleado_responsable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Titulo',
            new_name='titulo',
        ),
    ]
