# Generated by Django 5.1.1 on 2024-10-07 03:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0005_rename_titulo_task_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Proyecto',
        ),
    ]
