# Generated by Django 5.1.1 on 2024-10-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0006_rename_task_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Fecha_De_Realizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
