# Generated by Django 5.1.1 on 2024-10-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0007_alter_proyecto_fecha_de_realizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='importante',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Publicar',
            field=models.BooleanField(default=False),
        ),
    ]
