# Generated by Django 5.1.1 on 2024-10-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0008_remove_proyecto_importante_proyecto_publicar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='Publicar',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Estatus_de_proyecto',
            field=models.CharField(choices=[('Si', 'Publicado'), ('No', 'No Publicado')], default='No', max_length=2),
        ),
    ]
