# Generated by Django 5.1.1 on 2024-10-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0009_remove_proyecto_publicar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Estatus_de_proyecto',
            field=models.CharField(choices=[('Si', 'Activo'), ('No', 'Inactivo')], default='No', max_length=2),
        ),
    ]
