# Generated by Django 5.1.1 on 2024-10-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0013_alter_imagenesdeproyecto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesdeproyecto',
            name='imagen',
            field=models.ImageField(default='sample_images/01sample_galeria_v1.png', upload_to='proyectos_galeria/'),
        ),
    ]
