# Generated by Django 5.1.1 on 2024-11-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0014_alter_imagenesdeproyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesdeproyecto',
            name='imagen',
            field=models.ImageField(default='images/sample.png', upload_to='proyectos_galeria/'),
        ),
    ]
