# Generated by Django 5.1.1 on 2024-11-14 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0016_alter_imagenesdeproyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='Portada_de_proyecto',
            field=models.ImageField(null=True, upload_to='proyectos_portada/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
