# Generated by Django 5.1.1 on 2024-11-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0017_alter_proyecto_portada_de_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesdeproyecto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='proyectos_galeria/'),
        ),
    ]
