# Generated by Django 5.1.1 on 2024-12-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupKL', '0020_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusDeProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6C757D', max_length=7)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='Estatus_de_proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='signupKL.estatusdeproyecto'),
        ),
    ]
