# Generated by Django 5.1.1 on 2025-01-02 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('signupKL', '0022_userprofile_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ultimo_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_recuperados', to='auth.group', verbose_name='Último grupo asignado'),
        ),
    ]
